version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rentalpw
      POSTGRES_DB: rentaldb
    ports: [ "5432:5432" ]

  redis:
    image: redis:7
    platform: linux/amd64
    ports: [ "6379:6379" ]

  backend:
    build: ../apps/backend
    env_file: ../.env.dev
    depends_on: [ db, redis ]
    ports: [ "8000:8000" ]
