apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: rental-backend
  template:
    metadata:
      labels:
        app: rental-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.imageRegistry }}/rental-backend:{{ .Values.imageTag }}"
        ports:
        - containerPort: 8000
